# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

plugins:
  - jekyll-paginate
  - jekyll-gist

# Setup
title:            Alex Richey
tagline:          'Web Developer'
description:      "I'm a web developer and occasional columnist based in NYC. I write about politics and code."
url:              http://alexrichey.com
baseurl:          /

author:
  name:           'Alex Richey'
  url:            https://twitter.com/AlexanderRichey

paginate:         3

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
