# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

plugins:
  - jekyll-paginate
  - jekyll-gist

# Setup
title:            Alex Richey
tagline:          "Software Engineer"
description:      "Software Engineer @ Meural"
url:              http://alexrichey.com
baseurl:          /

author:
  name:           'Alex Richey'
  url:            https://twitter.com/AlexanderRichey

paginate:         3

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
