[site]
  title = "Alex Richey | Blog"
  description = "Software engineer based in Seattle, WA. I write about politics and code."
  url = "https://alexrichey.com"

[directories]
  includes = "includes"
  pages = "pages"
  posts = "articles"
  public = "public"
  output = "build"

[defaults]
  pageTemplate = "page.html"
  postTemplate = "article.html"

[build]
  postsIndexPage = "index.html"
  postsPerPage = 100
  chromaTheme = "dracula"
  chromaLineNumbers = false
  rss = true
  hash = [".js", ".css"]
