[site]
  title = "Alex Richey"
  description = "Software engineer based in Seattle, WA. I write about politics and code."
  url = "https://alexrichey.com"

[directories]
  includes = "includes"
  pages = "pages"
  posts = "articles"
  public = "public"
  output = "build"

[defaults]
  pageTemplate = "page.html"
  postTemplate = "article.html"

[build]
  postsIndexPage = "index.html"
  postsPerPage = 5
  chromaTheme = "emacs"
  chromaLineNumbers = false
  chromaWithClasses = true
  rss = true
  hash = [".js", ".css"]
